/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist;

/**
 *
 * @author LENOVO
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu(String nama, String jabatan, String role) {
        initComponents();
        String n = nama;
        String j = jabatan;
        String r = role;
        txtNama.setText(n);
        txtRole.setText(r);
        txtJabatan.setText(j);
        cekRole();
    }
    
    public void cekRole(){
        if(txtRole.getText().equals("ADM")){
            btnUserSettings.setVisible(false);
        }
    }

    private FormMenu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnTaskList = new javax.swing.JButton();
        btnUserSettings = new javax.swing.JButton();
        txtRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome, ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Rima Regiani");
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        txtJabatan.setForeground(new java.awt.Color(255, 255, 255));
        txtJabatan.setText("- Staff Admin");
        jPanel1.add(txtJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(255, 153, 0));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        btnTaskList.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\clipboard.png")); // NOI18N
        btnTaskList.setText("Task List");
        btnTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskListActionPerformed(evt);
            }
        });
        jPanel1.add(btnTaskList, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 310, 80));

        btnUserSettings.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\settings.png")); // NOI18N
        btnUserSettings.setText("User Settings");
        btnUserSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSettingsActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 310, 80));

        txtRole.setForeground(new java.awt.Color(255, 255, 255));
        txtRole.setText("ADM");
        jPanel1.add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        FormLogin fb = new FormLogin();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskListActionPerformed
        // TODO add your handling code here:
        if(txtRole.getText().equals("MNG")){
            FormTaskList fb = new FormTaskList();
            fb.setVisible(true);
            this.setVisible(false);
        }else{
            String nama = txtNama.getText();
            FormViewTask fb = new FormViewTask(nama);
            fb.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnTaskListActionPerformed

    private void btnUserSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSettingsActionPerformed
        // TODO add your handling code here:
        FormRegist fb = new FormRegist();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUserSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnTaskList;
    private javax.swing.JButton btnUserSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtJabatan;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtRole;
    // End of variables declaration//GEN-END:variables
}
